entities:
  # Specify a designed protein chain
  # random number between 12 and 20 of designed residues (inclusive)
  - protein: 
      id: G
      sequence: 100..120

  # Specification of the target which is extracted from a .cif file
  - file:
      path: /n/home06/tbush/peptide_gen_pipeline/structures/3ch4-assembly1.cif
      # Which chain and residues in the .cif file to use as target (uses only chain A here)
      include:
        - chain:
            id: A
      # Which regions of the target the design should or should NOT bind to
      # Here we specify that the design should bind to residues 343, 344, and 251 on chain A
      # binding_types:
      #   - chain:
      #       id: A
      #       binding: 
      # Which regions of the target should have their structure specified
      # Here we specify that all included target residues should have their structure specified
      structure_groups: "all"
